"""
pytest_to_aspice.py
-------------------
Parses pytest JSON output and maps results to ASPICE SWQ.1
base practice evidence requirements.

Usage:
    pytest --json-report --json-report-file=report.json
    python pytest_to_aspice.py report.json

Output:
    aspice_swq_evidence.md
"""

import json
import sys
from datetime import datetime


def load_report(path: str) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def map_to_aspice(report: dict) -> dict:
    summary = report.get("summary", {})
    tests = report.get("tests", [])

    passed = summary.get("passed", 0)
    failed = summary.get("failed", 0)
    errors = summary.get("errors", 0)
    total = summary.get("total", 0)
    duration = report.get("duration", 0)

    failed_tests = [
        t for t in tests if t.get("outcome") == "failed"
    ]

    pass_rate = (passed / total * 100) if total > 0 else 0

    verdict = "PASS" if failed == 0 and errors == 0 else \
              "PARTIAL" if pass_rate >= 80 else "FAIL"

    return {
        "timestamp": datetime.now().isoformat(),
        "total": total,
        "passed": passed,
        "failed": failed,
        "errors": errors,
        "pass_rate": round(pass_rate, 2),
        "duration_sec": round(duration, 2),
        "failed_tests": [t.get("nodeid") for t in failed_tests],
        "bp3_verdict": verdict,
        "bp4_deviations": len(failed_tests),
    }


def generate_markdown(data: dict) -> str:
    lines = [
        "# ASPICE SWQ.1 — Evidence Record",
        f"\n**Generated:** {data['timestamp']}",
        f"**Tool:** pytest\n",
        "## BP3 — Work Product Quality Assessment",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Total Tests | {data['total']} |",
        f"| Passed | {data['passed']} |",
        f"| Failed | {data['failed']} |",
        f"| Errors | {data['errors']} |",
        f"| Pass Rate | {data['pass_rate']}% |",
        f"| Duration | {data['duration_sec']}s |",
        f"\n**BP3 Verdict:** `{data['bp3_verdict']}`\n",
        "## BP4 — Process Deviation Log",
    ]

    if data["failed_tests"]:
        lines.append("\nThe following test cases require corrective action:\n")
        for t in data["failed_tests"]:
            lines.append(f"- `{t}`")
    else:
        lines.append("\nNo deviations recorded. All test cases passed.")

    lines.append(
        f"\n---\n*Generated by aspice-oss-validator — "
        f"https://github.com/your-username/aspice-oss-validator*"
    )

    return "\n".join(lines)


def main():
    if len(sys.argv) < 2:
        print("Usage: python pytest_to_aspice.py <report.json>")
        sys.exit(1)

    report = load_report(sys.argv[1])
    data = map_to_aspice(report)
    markdown = generate_markdown(data)

    output_path = "aspice_swq_evidence.md"
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(markdown)

    print(f"Evidence record written to: {output_path}")
    print(f"BP3 Verdict: {data['bp3_verdict']}")


if __name__ == "__main__":
    main()
  Commit Message: Add pytest-to-ASPICE parser
